"""Pass 3: turn HLIR (with addresses) into real PLENA ISA text.

Each HLIR op kind has a small dispatcher that pulls the right addresses
off the buffers and forwards them to ISAEmitter. This is intentionally
mechanical -- if you add a new op kind to `intrinsics.py`, you add one
case here too.

For BTMM specifically, the runtime convention is:
    - the actual `M_BTMM` instruction takes packed lhs (vram) + rhs (mram)
    - it does NOT itself write the result; the result is committed to
      VRAM by a paired `M_BMM_WO` instruction
The HLIR view collapses this to one `btmm` op that names lhs/rhs/dst;
this pass expands it into the `emit_btmm` + `emit_btmm_wo` pair so the
emitter contract is honoured.
"""

from __future__ import annotations

from typing import Any, Callable, Dict, List, Tuple

from tvm import tir

from . import hlir as _hlir
from . import scope as _scope
from .expr_materializer import ExprMaterializer, MaterializedExpr
from .isa_emitter import ISAEmitter
from .program_shim import ProgramShim


class IsaEmissionError(RuntimeError):
    pass


class IsaEmitterPass:
    def __init__(self, shim: ProgramShim) -> None:
        self.shim = shim
        self.emitter = ISAEmitter(shim)
        # Symbol table: tir.Var -> currently-bound GP register id. Loop
        # bodies push entries on enter and pop on exit. ExprMaterializer
        # consults this table to resolve Var references in scalar args.
        self.symbol_table: Dict[tir.Var, int] = {}
        self.materializer = ExprMaterializer(shim, self.symbol_table)
        self._dispatch: Dict[str, Callable[[_hlir.HLIRModule, _hlir.Op], None]] = {
            "dma_h2v": self._emit_dma_h2v,
            "dma_h2m": self._emit_dma_h2m,
            "dma_v2h": self._emit_dma_v2h,
            "dma_h2v_slice": self._emit_dma_h2v_slice,
            "dma_h2m_slice": self._emit_dma_h2m_slice,
            "dma_v2h_slice": self._emit_dma_v2h_slice,
            "btmm": self._emit_btmm,
            "mm": self._emit_mm,
            "mm_slot": self._emit_mm_slot,
            "zero_v": self._emit_zero_v,
            "v_add": self._emit_v_add,
            "map_fp_to_v": self._emit_map_fp_to_v,
            "map_v_to_fp": self._emit_map_v_to_fp,
            "fp_copy": self._emit_fp_copy,
            "fp_copy_at": self._emit_fp_copy_at,
            "fp_add": self._emit_fp_add,
            "fp_add_at": self._emit_fp_add_at,
            "fp_sub": self._emit_fp_sub,
            "fp_sub_at": self._emit_fp_sub_at,
            "fp_mul": self._emit_fp_mul,
            "fp_mul_at": self._emit_fp_mul_at,
            "fp_max": self._emit_fp_max,
            "fp_max_at": self._emit_fp_max_at,
            "fp_exp": self._emit_fp_exp,
            "fp_exp_at": self._emit_fp_exp_at,
            "fp_reci": self._emit_fp_reci,
            "fp_reci_at": self._emit_fp_reci_at,
            "fp_sqrt": self._emit_fp_sqrt,
            "fp_sqrt_at": self._emit_fp_sqrt_at,
            "row_reduce_max": self._emit_row_reduce_max,
            "row_reduce_sum": self._emit_row_reduce_sum,
            "row_exp": self._emit_row_exp,
            "row_reci": self._emit_row_reci,
            "row_add_fp": self._emit_row_add_fp,
            "row_sub_fp": self._emit_row_sub_fp,
            "row_mul_fp": self._emit_row_mul_fp,
            "row_reduce_max_mask": self._emit_row_reduce_max_mask,
            "row_reduce_sum_mask": self._emit_row_reduce_sum_mask,
            "row_exp_mask": self._emit_row_exp_mask,
            "row_reci_mask": self._emit_row_reci_mask,
            "row_add_fp_mask": self._emit_row_add_fp_mask,
            "row_sub_fp_mask": self._emit_row_sub_fp_mask,
            "row_mul_fp_mask": self._emit_row_mul_fp_mask,
            "row_reduce_max_at": self._emit_row_reduce_max_at,
            "row_reduce_sum_at": self._emit_row_reduce_sum_at,
            "row_exp_at": self._emit_row_exp_at,
            "row_sub_fp_at": self._emit_row_sub_fp_at,
            "row_mul_fp_at": self._emit_row_mul_fp_at,
            "row_add_fp_at": self._emit_row_add_fp_at,
            "for": self._emit_for,
        }

    def run(self, mod: _hlir.HLIRModule) -> str:
        _hlir.assert_addresses_resolved(mod)
        # Emit a header so generated dumps are easy to identify in build/.
        self.shim.compiler.generated_code = (
            f"; PLENA ISA  --  kernel: {mod.name}\n"
            f"; generated by tilelang_tvm_compiler (real-ISA path)\n"
            f"; ============================================================\n"
            f"; buffer layout:\n"
        )
        for buf in mod.buffers.values():
            self.shim.compiler.generated_code += (
                f";   {buf.name:<10s} scope={buf.scope:<5s} addr={buf.address}  "
                f"shape={'x'.join(str(s) for s in buf.shape)}\n"
            )
        self.shim.compiler.generated_code += (
            "; ============================================================\n\n"
        )

        for op in mod.ops:
            handler = self._dispatch.get(op.kind)
            if handler is None:
                raise IsaEmissionError(
                    f"no ISA dispatcher for HLIR op kind {op.kind!r}. "
                    f"Either add it to isa_pass dispatch table, or guard "
                    f"the op out of HLIR earlier."
                )
            handler(mod, op)
        return self.shim.compiler.generated_code

    @staticmethod
    def _logical_2d(shape: Tuple[int, ...]) -> Tuple[int, int]:
        if not shape:
            return (1, 1)
        if len(shape) == 1:
            return (1, int(shape[0]))
        if len(shape) == 2:
            return (int(shape[0]), int(shape[1]))
        rows = 1
        for dim in shape[:-2]:
            rows *= int(dim)
        cols = int(shape[-2]) * int(shape[-1])
        return (rows, cols)

    @staticmethod
    def _flat_addrs(buf: _hlir.Buffer) -> List[int]:
        return [int(buf.address) + i for i in range(buf.num_elements)]

    def _fpram_buf_addrs(self, buf: _hlir.Buffer, op_kind: str, role: str) -> List[int]:
        _check_scope(buf, _scope.FPRAM, op_kind, role)
        return self._flat_addrs(buf)

    def _vram_row_shape(self, buf: _hlir.Buffer, op_kind: str, role: str) -> Tuple[int, int]:
        _check_scope(buf, _scope.VRAM, op_kind, role)
        rows, cols = self._logical_2d(buf.shape)
        if cols != self.shim.mlen:
            raise IsaEmissionError(
                f"{op_kind} {role} buffer {buf.name!r} must have logical row width "
                f"mlen={self.shim.mlen}; got logical 2D ({rows}, {cols})"
            )
        return rows, cols

    def _resolve_row_at_coords(
        self,
        buf: _hlir.Buffer,
        op_kind: str,
        role: str,
        dim2_expr,
        dim3_expr,
    ) -> Tuple[tir.PrimExpr, tir.PrimExpr, tir.PrimExpr, tir.PrimExpr | None]:
        _check_scope(buf, _scope.VRAM, op_kind, role)
        if len(buf.shape) != 4:
            raise IsaEmissionError(
                f"{op_kind} {role} buffer {buf.name!r} must be 4D for logical (dim2, dim3) addressing; "
                f"got shape={buf.shape}"
            )
        if int(buf.shape[0]) != 1:
            raise IsaEmissionError(
                f"{op_kind} {role} buffer {buf.name!r} currently requires batch dimension 1; "
                f"got shape={buf.shape}"
            )

        if int(buf.shape[-1]) == int(self.shim.mlen):
            # Full-width rows: each logical (dim2, dim3) pair names one mlen-wide
            # vector directly, with dim2 selecting the head-like outer group.
            row_stride = tir.IntImm("int32", int(buf.shape[2]))
            vram_row_expr = tir.Add(tir.Mul(dim2_expr, row_stride), dim3_expr)
            fp_row_expr = dim3_expr
            fp_head_expr = dim2_expr
            mask_expr = None
        else:
            packed_heads = int(buf.shape[2])
            packed_width = int(buf.shape[3])
            if packed_heads * packed_width != int(self.shim.mlen):
                raise IsaEmissionError(
                    f"{op_kind} {role} buffer {buf.name!r} has narrow D={packed_width} but does not pack "
                    f"one full mlen row across dim3; shape={buf.shape}, mlen={self.shim.mlen}"
                )
            # Packed narrow rows: dim2 selects the physical row, dim3 selects the
            # head slot within that row. Emit a V_MASK for that slot.
            vram_row_expr = dim2_expr
            fp_row_expr = dim2_expr
            fp_head_expr = dim3_expr
            mask_expr = tir.shift_left(tir.IntImm("int32", 1), dim3_expr)

        return vram_row_expr, fp_head_expr, fp_row_expr, mask_expr

    def _emit_fp_kernel_op(
        self,
        mod: _hlir.HLIRModule,
        op: _hlir.Op,
        *,
        kernel_op: str,
    ) -> None:
        if kernel_op in {"copy", "exp", "reci", "sqrt"}:
            src = mod.get_buffer(op.buffer_args[0])
            dst = mod.get_buffer(op.buffer_args[1])
            src_addrs = self._fpram_buf_addrs(src, op.kind, "src")
            dst_addrs = self._fpram_buf_addrs(dst, op.kind, "dst")
            if len(src_addrs) != len(dst_addrs):
                raise IsaEmissionError(
                    f"{op.kind} src/dst lengths must match; got "
                    f"{len(src_addrs)} and {len(dst_addrs)}"
                )
            self.emitter.emit_fp_kernel(
                src1_addrs=src_addrs,
                dst_addrs=dst_addrs,
                op=kernel_op,
                task_id=op.annotations.get("intrinsic", op.kind),
            )
            return

        lhs = mod.get_buffer(op.buffer_args[0])
        rhs = mod.get_buffer(op.buffer_args[1])
        dst = mod.get_buffer(op.buffer_args[2])
        lhs_addrs = self._fpram_buf_addrs(lhs, op.kind, "lhs")
        rhs_addrs = self._fpram_buf_addrs(rhs, op.kind, "rhs")
        dst_addrs = self._fpram_buf_addrs(dst, op.kind, "dst")
        if not (len(lhs_addrs) == len(rhs_addrs) == len(dst_addrs)):
            raise IsaEmissionError(
                f"{op.kind} lhs/rhs/dst lengths must match; got "
                f"{len(lhs_addrs)}, {len(rhs_addrs)}, {len(dst_addrs)}"
            )
        self.emitter.emit_fp_kernel(
            src1_addrs=lhs_addrs,
            src2_addrs=rhs_addrs,
            dst_addrs=dst_addrs,
            op=kernel_op,
            task_id=op.annotations.get("intrinsic", op.kind),
        )

    def _emit_fp_scalar_op_at(
        self,
        mod: _hlir.HLIRModule,
        op: _hlir.Op,
        *,
        kernel_op: str,
    ) -> None:
        row_expr = op.scalar_args[0]
        ra = self.shim.compiler.register_allocator
        mats = []

        # Materialize the row-offset expression ONCE, then derive each
        # buffer's address with a single S_ADDI_INT (buf.address fits in the
        # 12-bit immediate). Without this we'd recompute the full row_expr
        # (e.g. `lane*64 + row` -> SLLI + ADD) per buffer, ballooning the
        # inner-loop body and tripping the emulator's MAX_LOOP_INSTRUCTIONS.
        m_row = self.materializer.materialize(row_expr)
        self.shim.compiler.generated_code += m_row.isa
        mats.append(m_row)
        gp_row = m_row.register

        def _addr_reg(buf_name):
            buf = mod.get_buffer(buf_name)
            _check_scope(buf, _scope.FPRAM, op.kind, buf_name)
            r = ra.allocate_gp(1)[0]
            self.shim.compiler.generated_code += (
                f"S_ADDI_INT gp{r}, gp{gp_row}, {int(buf.address)}\n"
            )
            mats.append(MaterializedExpr(
                register=r, isa="", owns_register=True, _materializer=self.materializer
            ))
            return r

        regs = ra.allocate_gp(3)
        gp_a, gp_b, gp_c = regs
        try:
            if kernel_op in {"copy", "exp", "reci", "sqrt"}:
                gp_src = _addr_reg(op.buffer_args[0])
                gp_dst = _addr_reg(op.buffer_args[1])
                lines = [f"; fp scalar task {op.annotations.get('intrinsic', op.kind)} op={kernel_op}"]
                lines.append(f"S_ADDI_INT gp{gp_a}, gp{gp_src}, 0")
                lines.append(f"S_ADDI_INT gp{gp_c}, gp{gp_dst}, 0")
                lines.append(f"S_LD_FP f1, gp{gp_a}, 0")
                unary = {"exp": "S_EXP_FP", "reci": "S_RECI_FP", "sqrt": "S_SQRT_FP"}
                if kernel_op == "copy":
                    lines.append(f"S_ST_FP f1, gp{gp_c}, 0")
                elif kernel_op == "reci":
                    lines.append(f"S_RECI_FP f1, f1")
                    lines.append(f"S_ST_FP f1, gp{gp_c}, 0")
                elif kernel_op == "sqrt":
                    lines.append(f"S_SQRT_FP f1, f1")
                    lines.append(f"S_ST_FP f1, gp{gp_c}, 0")
                else:
                    lines.append("S_EXP_FP f1, f1, 0")
                    lines.append(f"S_ST_FP f1, gp{gp_c}, 0")
                self.shim.compiler.generated_code += "\n".join(lines) + "\n"
                return

            gp_lhs = _addr_reg(op.buffer_args[0])
            gp_rhs = _addr_reg(op.buffer_args[1])
            gp_dst = _addr_reg(op.buffer_args[2])
            opcode = {
                "add": "S_ADD_FP",
                "sub": "S_SUB_FP",
                "mul": "S_MUL_FP",
                "max": "S_MAX_FP",
            }[kernel_op]
            lines = [f"; fp scalar task {op.annotations.get('intrinsic', op.kind)} op={kernel_op}"]
            lines.append(f"S_ADDI_INT gp{gp_a}, gp{gp_lhs}, 0")
            lines.append(f"S_ADDI_INT gp{gp_b}, gp{gp_rhs}, 0")
            lines.append(f"S_ADDI_INT gp{gp_c}, gp{gp_dst}, 0")
            lines.append("S_LD_FP f1, gp{0}, 0".format(gp_a))
            lines.append("S_LD_FP f2, gp{0}, 0".format(gp_b))
            lines.append(f"{opcode} f1, f1, f2")
            lines.append(f"S_ST_FP f1, gp{gp_c}, 0")
            self.shim.compiler.generated_code += "\n".join(lines) + "\n"
        finally:
            for m in reversed(mats):
                m.release()
            ra.free_gp(regs)

    def _emit_row_scalar_op_at(
        self,
        mod: _hlir.HLIRModule,
        op: _hlir.Op,
        *,
        row_op: str,
        reduce: bool = False,
        masked: bool = False,
    ) -> None:
        src = mod.get_buffer(op.buffer_args[0])
        _check_scope(src, _scope.VRAM, op.kind, "src")
        has_fp = reduce or len(op.buffer_args) == 3
        expected_scalars = 2
        if len(op.scalar_args) != expected_scalars:
            raise IsaEmissionError(
                f"{op.kind} expects {expected_scalars} scalar args, got {len(op.scalar_args)}"
            )
        dim2_expr = op.scalar_args[0]
        dim3_expr = op.scalar_args[1]
        src_row_expr, fp_head_expr, fp_row_expr, mask_expr = self._resolve_row_at_coords(
            src, op.kind, "src", dim2_expr, dim3_expr
        )
        ra = self.shim.compiler.register_allocator
        mats = []

        emit_v_mask = masked and mask_expr is not None
        use_mask_flag = 1 if emit_v_mask else 0

        row_addr_expr = tir.Add(
            tir.IntImm("int32", int(src.address)),
            tir.Mul(src_row_expr, tir.IntImm("int32", int(self.shim.mlen))),
        )
        m_src = self.materializer.materialize(row_addr_expr)
        self.shim.compiler.generated_code += m_src.isa
        mats.append(m_src)
        gp_src = m_src.register

        def _fp_offset_expr(fp_buf) -> tir.PrimExpr:
            base = tir.IntImm("int32", int(fp_buf.address))
            inner = tir.IntImm("int32", int(fp_buf.shape[-1]))
            return tir.Add(
                base,
                tir.Add(tir.Mul(fp_head_expr, inner), fp_row_expr),
            )

        gp_mask = None
        regs = ra.allocate_gp(3)
        gp_a, gp_b, gp_c = regs
        try:
            lines = [f"; row scalar task {op.annotations.get('intrinsic', op.kind)} op={row_op}"]
            if emit_v_mask:
                m_mask = self.materializer.materialize(mask_expr)
                self.shim.compiler.generated_code += m_mask.isa
                mats.append(m_mask)
                gp_mask = m_mask.register
                lines.append(f"C_SET_V_MASK_REG gp{gp_mask}")

            if reduce:
                dst = mod.get_buffer(op.buffer_args[1])
                _check_scope(dst, _scope.FPRAM, op.kind, "dst")
                dst_expr = _fp_offset_expr(dst)
                m_dst = self.materializer.materialize(dst_expr)
                self.shim.compiler.generated_code += m_dst.isa
                mats.append(m_dst)
                lines.append(f"S_ADDI_INT gp{gp_a}, gp{m_dst.register}, 0")
                lines.append("S_LD_FP f1, gp{0}, 0".format(gp_a))
                opcode = {"reduce_max": "V_RED_MAX", "reduce_sum": "V_RED_SUM"}[row_op]
                lines.append(f"{opcode} f1, gp{gp_src}, {use_mask_flag}")
                lines.append(f"S_ST_FP f1, gp{gp_a}, 0")
            elif len(op.buffer_args) == 2:
                dst = mod.get_buffer(op.buffer_args[1])
                _check_scope(dst, _scope.VRAM, op.kind, "dst")
                dst_row_expr, _, _, dst_mask_expr = self._resolve_row_at_coords(
                    dst, op.kind, "dst", dim2_expr, dim3_expr
                )
                if emit_v_mask and dst_mask_expr is None:
                    raise IsaEmissionError(
                        f"{op.kind} src requires packed-head mask but dst {dst.name!r} does not"
                    )
                dst_row_expr = tir.Add(
                    tir.IntImm("int32", int(dst.address)),
                    tir.Mul(dst_row_expr, tir.IntImm("int32", int(self.shim.mlen))),
                )
                m_dst = self.materializer.materialize(dst_row_expr)
                self.shim.compiler.generated_code += m_dst.isa
                mats.append(m_dst)
                opcode = {"exp": "V_EXP_V", "reci": "V_RECI_V"}[row_op]
                lines.append(f"{opcode} gp{m_dst.register}, gp{gp_src}, {use_mask_flag}")
            else:
                rhs = mod.get_buffer(op.buffer_args[1])
                dst = mod.get_buffer(op.buffer_args[2])
                _check_scope(rhs, _scope.FPRAM, op.kind, "rhs")
                _check_scope(dst, _scope.VRAM, op.kind, "dst")
                dst_row_expr, _, _, dst_mask_expr = self._resolve_row_at_coords(
                    dst, op.kind, "dst", dim2_expr, dim3_expr
                )
                if emit_v_mask and dst_mask_expr is None:
                    raise IsaEmissionError(
                        f"{op.kind} src requires packed-head mask but dst {dst.name!r} does not"
                    )
                rhs_expr = _fp_offset_expr(rhs)
                dst_row_expr = tir.Add(
                    tir.IntImm("int32", int(dst.address)),
                    tir.Mul(dst_row_expr, tir.IntImm("int32", int(self.shim.mlen))),
                )
                m_rhs = self.materializer.materialize(rhs_expr)
                self.shim.compiler.generated_code += m_rhs.isa
                mats.append(m_rhs)
                m_dst = self.materializer.materialize(dst_row_expr)
                self.shim.compiler.generated_code += m_dst.isa
                mats.append(m_dst)
                lines.append(f"S_ADDI_INT gp{gp_b}, gp{m_rhs.register}, 0")
                lines.append("S_LD_FP f1, gp{0}, 0".format(gp_b))
                if row_op == "sub":
                    lines.append(f"V_SUB_VF gp{m_dst.register}, gp{gp_src}, f1, {use_mask_flag}, 0")
                else:
                    opcode = {"add": "V_ADD_VF", "mul": "V_MUL_VF"}[row_op]
                    lines.append(f"{opcode} gp{m_dst.register}, gp{gp_src}, f1, {use_mask_flag}")

            if emit_v_mask:
                lines.append(f"S_ADDI_INT gp{gp_mask}, gp0, 0")
                lines.append(f"C_SET_V_MASK_REG gp{gp_mask}")
            self.shim.compiler.generated_code += "\n".join(lines) + "\n"
        finally:
            for m in reversed(mats):
                m.release()
            ra.free_gp(regs)

    def _emit_row_scalar_op(
        self,
        mod: _hlir.HLIRModule,
        op: _hlir.Op,
        *,
        row_op: str,
        reduce: bool = False,
        masked: bool = False,
    ) -> None:
        src = mod.get_buffer(op.buffer_args[0])
        row_count, _ = self._vram_row_shape(src, op.kind, "src")
        expected_scalar_count = 1 if masked else 0
        if len(op.scalar_args) != expected_scalar_count:
            raise IsaEmissionError(
                f"{op.kind} expects {expected_scalar_count} scalar args, got {len(op.scalar_args)}"
            )
        mask_val = None
        if masked:
            try:
                mask_val = int(op.scalar_args[0])
            except TypeError as exc:
                raise IsaEmissionError(
                    f"{op.kind} mask must be a compile-time integer, got "
                    f"{type(op.scalar_args[0]).__name__}: {op.scalar_args[0]!r}"
                ) from exc
        if reduce:
            dst = mod.get_buffer(op.buffer_args[1])
            dst_addrs = self._fpram_buf_addrs(dst, op.kind, "dst")
            if len(dst_addrs) != row_count:
                raise IsaEmissionError(
                    f"{op.kind} dst fpram length must equal row_count={row_count}; "
                    f"got {len(dst_addrs)} for buffer {dst.name}"
                )
            self.emitter.emit_row_operation(
                src_vram_addr=src.address,
                op=row_op,
                row_count=row_count,
                dst_addrs=dst_addrs,
                mask_val=mask_val,
                task_id=op.annotations.get("intrinsic", op.kind),
            )
            return

        if len(op.buffer_args) == 2:
            dst = mod.get_buffer(op.buffer_args[1])
            dst_rows, _ = self._vram_row_shape(dst, op.kind, "dst")
            if dst_rows != row_count:
                raise IsaEmissionError(
                    f"{op.kind} src/dst row counts must match; got {row_count} and {dst_rows}"
                )
            self.emitter.emit_row_operation(
                src_vram_addr=src.address,
                dst_vram_addr=dst.address,
                op=row_op,
                row_count=row_count,
                mask_val=mask_val,
                task_id=op.annotations.get("intrinsic", op.kind),
            )
            return

        rhs = mod.get_buffer(op.buffer_args[1])
        dst = mod.get_buffer(op.buffer_args[2])
        dst_rows, _ = self._vram_row_shape(dst, op.kind, "dst")
        if dst_rows != row_count:
            raise IsaEmissionError(
                f"{op.kind} src/dst row counts must match; got {row_count} and {dst_rows}"
            )
        rhs_addrs = self._fpram_buf_addrs(rhs, op.kind, "rhs")
        if len(rhs_addrs) not in (1, row_count):
            raise IsaEmissionError(
                f"{op.kind} rhs fpram length must be 1 or row_count={row_count}; "
                f"got {len(rhs_addrs)} for buffer {rhs.name}"
            )
        self.emitter.emit_row_operation(
            src_vram_addr=src.address,
            dst_vram_addr=dst.address,
            op=row_op,
            row_count=row_count,
            rhs_addrs=rhs_addrs,
            mask_val=mask_val,
            task_id=op.annotations.get("intrinsic", op.kind),
        )

    # ------------------------------------------------------------------
    # Per-op dispatchers. Each one is a thin glue between HLIR buffer
    # references and ISAEmitter's positional/keyword API.
    # ------------------------------------------------------------------
    # ---- DMA decomposition --------------------------------------------
    # Each emit_load/store_tile_from_hbm transfers exactly ONE mlen x mlen
    # tile. For HBM buffers whose logical 2D shape spans multiple tiles
    # we issue one ISA emit call per tile, walking the buffer in
    # col-block-major order (matches --stage-output / runtime helper).
    def _iter_tile_offsets(self, hbm_buf: _hlir.Buffer):
        """Yield (vram_offset_elems, hbm_offset_elems) for each tile of buf."""
        mlen = self.shim.mlen
        ann = hbm_buf.annotations
        rows = ann.get("logical_rows", mlen)
        cols = ann.get("logical_cols", mlen)
        row_blocks = ann.get("row_blocks", 1)
        col_blocks = ann.get("col_blocks", 1)
        tile_elems = mlen * mlen
        idx = 0
        for j in range(col_blocks):
            for i in range(row_blocks):
                # HBM offset (in elements) of the (i,j) tile within this
                # logical 2D buffer. Logical layout is row-major so column
                # j contributes j*mlen, row i contributes i*mlen*cols.
                hbm_off = i * mlen * cols + j * mlen
                vram_off = idx * tile_elems
                yield vram_off, hbm_off
                idx += 1

    def _emit_dma_h2v(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        src = mod.get_buffer(op.buffer_args[0])
        dst = mod.get_buffer(op.buffer_args[1])
        _check_scope(src, _scope.HBM, op.kind, "src")
        _check_scope(dst, _scope.VRAM, op.kind, "dst")
        for vram_off, hbm_off in self._iter_tile_offsets(src):
            self.shim.compiler.generated_code += (
                f"; dma_h2v tile  {src.name}[hbm+{hbm_off}] -> "
                f"{dst.name}[vram+{vram_off}]\n"
            )
            self.emitter.emit_load_tile_from_hbm(
                hbm_addr=src.address,
                vram_addr=dst.address + vram_off,
                hbm_stride=src.hbm_stride,
                hbm_scale_size=src.hbm_scale_size,
                hbm_start_offset=src.hbm_offset + hbm_off,
            )

    def _emit_dma_h2m(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        src = mod.get_buffer(op.buffer_args[0])
        dst = mod.get_buffer(op.buffer_args[1])
        _check_scope(src, _scope.HBM, op.kind, "src")
        _check_scope(dst, _scope.MRAM, op.kind, "dst")
        for vram_off, hbm_off in self._iter_tile_offsets(src):
            self.shim.compiler.generated_code += (
                f"; dma_h2m tile  {src.name}[hbm+{hbm_off}] -> "
                f"{dst.name}[mram+{vram_off}]\n"
            )
            self.emitter.emit_hbm_tile_to_mram(
                hbm_addr=src.address,
                mram_addr=dst.address + vram_off,
                hbm_offset=src.hbm_offset + hbm_off,
                hbm_scale=src.hbm_scale_size,
                hbm_stride=src.hbm_stride,
            )

    def _emit_dma_v2h(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        # Convention: HBM buffers are BSHD; VRAM buffers may be BHSD if
        # they came out of BTMM/BMM_WO (head-major physical layout). This
        # iteration walks the HBM (dst) in col-block-major order, which
        # happens to land vram_off = idx * tile_elems on each head's tile
        # boundary -- exactly matching BMM_WO's BHSD VRAM packing. The
        # store thus reorders BHSD -> BSHD as a side-effect of the walk.
        src = mod.get_buffer(op.buffer_args[0])
        dst = mod.get_buffer(op.buffer_args[1])
        _check_scope(src, _scope.VRAM, op.kind, "src")
        _check_scope(dst, _scope.HBM, op.kind, "dst")
        if src.num_elements != dst.num_elements:
            raise IsaEmissionError(
                f"dma_v2h: src ({src.name}, {src.num_elements} elems) and dst "
                f"({dst.name}, {dst.num_elements} elems) must have the same total "
                f"size, but their layouts may differ (VRAM=BHSD, HBM=BSHD)."
            )
        for vram_off, hbm_off in self._iter_tile_offsets(dst):
            self.shim.compiler.generated_code += (
                f"; dma_v2h tile  {src.name}[vram+{vram_off}] -> "
                f"{dst.name}[hbm+{hbm_off}]\n"
            )
            self.emitter.emit_store_tile_to_hbm(
                vram_addr=src.address + vram_off,
                hbm_addr=dst.address,
                hbm_stride=dst.hbm_stride,
                hbm_scale_size=dst.hbm_scale_size,
                hbm_start_offset=dst.hbm_offset + hbm_off,
            )

    # ------------------------------------------------------------------
    # Sliced DMA dispatchers. The slice is one of buffer_args (src or
    # dst depending on direction). For now we restrict to STATIC starts
    # (all Python ints / IntImm); dynamic starts (PrimExpr) raise a
    # clear error pointing at the next phase.
    # ------------------------------------------------------------------
    def _slice_offset_static(
        self, parent: _hlir.Buffer, sl: _hlir.BufferSlice,
    ) -> int:
        """Same math as `_build_slice_offset_expr`, restricted to all-int
        starts. Used in the static fast-path (avoids the extra
        S_ADDI_INT...mov that the dynamic path inserts)."""
        offset = 0
        shape = parent.shape
        for i, s in enumerate(sl.starts):
            stride_below = 1
            for d in shape[i + 1:]:
                stride_below *= int(d)
            offset += int(s) * stride_below
        return offset

    @staticmethod
    def _slice_has_dynamic_start(sl: _hlir.BufferSlice) -> bool:
        return any(not isinstance(s, int) for s in sl.starts)

    def _build_slice_offset_expr(
        self, parent: _hlir.Buffer, sl: _hlir.BufferSlice,
    ):
        """Build a PrimExpr for the slice's element offset in `parent`'s
        HBM region. Mixes static (Python int / IntImm) and dynamic
        (PrimExpr) starts uniformly. ExprMaterializer's constant
        folding will collapse static sub-trees automatically.
        """
        offset = tir.IntImm("int32", 0)
        shape = parent.shape
        for i, s in enumerate(sl.starts):
            stride_below = 1
            for d in shape[i + 1:]:
                stride_below *= int(d)
            if isinstance(s, int):
                term = tir.IntImm("int32", s * stride_below)
            else:
                # `s` is a PrimExpr (loop var or compound); multiply by
                # stride at the IR level so the materialiser can apply
                # strength reduction (e.g. SLLI when stride is 2^k).
                term = s * tir.IntImm("int32", stride_below)
            offset = offset + term
        return offset

    def _check_slice_single_tile(
        self, parent: _hlir.Buffer, sl: _hlir.BufferSlice,
    ) -> None:
        """For input slices (h2v / h2m): must fit in exactly one mlen*mlen
        tile after H*D logical-2D collapse, since the destination
        VRAM/MRAM buffer is a single-tile staging area.
        """
        mlen = self.shim.mlen
        ext = sl.extents
        if len(ext) != len(parent.shape):
            raise IsaEmissionError(
                f"slice on {parent.name!r}: extents length {len(ext)} != "
                f"parent ndim {len(parent.shape)}"
            )
        if len(ext) >= 3:
            rows = 1
            for e in ext[:-2]:
                rows *= int(e)
            cols = int(ext[-2]) * int(ext[-1])
        elif len(ext) == 2:
            rows, cols = int(ext[0]), int(ext[1])
        else:
            rows, cols = 1, int(ext[0])
        if rows != mlen or cols != mlen:
            raise IsaEmissionError(
                f"slice on {parent.name!r} extents={ext} maps to logical 2D "
                f"({rows}, {cols}); h2v/h2m input slices must fit a single "
                f"mlen*mlen tile."
            )

    def _iter_slice_tiles_per_head(self, parent: _hlir.Buffer, sl: _hlir.BufferSlice):
        """Per-head multi-tile iterator for v2h-slice writeback.

        Used when the slice covers `eh` heads but a single mlen-aligned
        block in seq and dim dims. Each tile is one head's contribution.
        Yields tuples `(h_idx, vram_off_in_src, tile_const_in_parent_elems)`:
            * `h_idx`            -- which head within the slice (0..eh-1)
            * `vram_off_in_src`  -- offset in elements from the VRAM source
                                    buffer's base. Assumes BHSD physical
                                    layout (BMM_WO output convention),
                                    where head h's tile sits at
                                    `h * tile_elems`.
            * `tile_const_in_parent_elems` -- additive offset to combine
                                    with the slice's BASE offset to land
                                    at this tile's element 0 in the parent.

        Constraints (matches the v2h_slice dispatcher's expectations):
            * parent is 4D BSHD
            * eb == 1 (single batch)
            * es == mlen (single seq tile per head)
            * ed == mlen (single dim tile per head)
            * eh >= 1 (any number of heads; eh > 1 is the multi-tile case)
        """
        mlen = self.shim.mlen
        if len(parent.shape) != 4:
            raise IsaEmissionError(
                f"per-head slice tiling requires 4D BSHD parent; got "
                f"shape {parent.shape}"
            )
        B, S, H, D = parent.shape
        eb, es, eh, ed = sl.extents
        if eb != 1:
            raise IsaEmissionError(
                f"per-head slice tiling does not support batch slicing "
                f"(eb={eb})"
            )
        if es != mlen:
            raise IsaEmissionError(
                f"per-head slice tiling requires es == mlen ({mlen}); "
                f"got es={es}"
            )
        if ed != mlen:
            raise IsaEmissionError(
                f"per-head slice tiling requires ed == mlen ({mlen}); "
                f"got ed={ed}"
            )
        if eh < 1:
            raise IsaEmissionError(f"slice has no heads to iterate (eh={eh})")
        tile_elems = mlen * mlen
        for h_idx in range(eh):
            yield h_idx, h_idx * tile_elems, h_idx * int(D)

    def _slice_is_single_logical_tile(
        self, parent: _hlir.Buffer, sl: _hlir.BufferSlice,
    ) -> bool:
        ext = sl.extents
        if len(ext) != len(parent.shape):
            return False
        if len(ext) >= 3:
            rows = 1
            for e in ext[:-2]:
                rows *= int(e)
            cols = int(ext[-2]) * int(ext[-1])
        elif len(ext) == 2:
            rows, cols = int(ext[0]), int(ext[1])
        else:
            rows, cols = 1, int(ext[0])
        return rows == self.shim.mlen and cols == self.shim.mlen

    def _materialise_slice_offset(
        self, parent: _hlir.Buffer, sl: _hlir.BufferSlice,
    ):
        """Returns either:
            (None, int_offset)  -- all starts static; caller uses
                                    existing int-offset emit path.
            (MaterializedExpr, None) -- dynamic; caller uses *_reg emit
                                    path and must release the result.
        """
        if not self._slice_has_dynamic_start(sl):
            return None, parent.hbm_offset + self._slice_offset_static(parent, sl)
        # Dynamic path: build expr (includes parent.hbm_offset for safety)
        # and lower via ExprMaterializer.
        expr = self._build_slice_offset_expr(parent, sl)
        if parent.hbm_offset:
            expr = expr + tir.IntImm("int32", parent.hbm_offset)
        m = self.materializer.materialize(expr)
        self.shim.compiler.generated_code += m.isa
        return m, None

    @staticmethod
    def _format_starts(sl: _hlir.BufferSlice) -> str:
        return ",".join(
            str(s) if isinstance(s, int) else f"<{type(s).__name__}>"
            for s in sl.starts
        )

    def _emit_dma_h2v_slice(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        sl = op.buffer_args[0]
        dst = mod.get_buffer(op.buffer_args[1])
        if not isinstance(sl, _hlir.BufferSlice):
            raise IsaEmissionError(
                f"dma_h2v_slice: buffer_args[0] must be BufferSlice, got "
                f"{type(sl).__name__}"
            )
        parent = mod.get_buffer(sl.parent)
        _check_scope(parent, _scope.HBM, op.kind, "src.parent")
        _check_scope(dst, _scope.VRAM, op.kind, "dst")
        self._check_slice_single_tile(parent, sl)

        m_off, static_off = self._materialise_slice_offset(parent, sl)
        starts_s = self._format_starts(sl)
        if m_off is None:
            self.shim.compiler.generated_code += (
                f"; dma_h2v_slice  {parent.name}[{starts_s}]+{list(sl.extents)} "
                f"-> {dst.name}  (parent_off={static_off} elems)\n"
            )
            self.emitter.emit_load_tile_from_hbm(
                hbm_addr=parent.address, vram_addr=dst.address,
                hbm_stride=parent.hbm_stride, hbm_scale_size=parent.hbm_scale_size,
                hbm_start_offset=static_off,
            )
        else:
            self.shim.compiler.generated_code += (
                f"; dma_h2v_slice  {parent.name}[{starts_s}]+{list(sl.extents)} "
                f"-> {dst.name}  (parent_off=gp{m_off.register} dyn)\n"
            )
            self.emitter.emit_load_tile_from_hbm(
                hbm_addr=parent.address, vram_addr=dst.address,
                hbm_stride=parent.hbm_stride, hbm_scale_size=parent.hbm_scale_size,
                hbm_start_offset_reg=m_off.register,
            )
            m_off.release()

    def _emit_dma_h2m_slice(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        sl = op.buffer_args[0]
        dst = mod.get_buffer(op.buffer_args[1])
        if not isinstance(sl, _hlir.BufferSlice):
            raise IsaEmissionError(
                f"dma_h2m_slice: buffer_args[0] must be BufferSlice"
            )
        parent = mod.get_buffer(sl.parent)
        _check_scope(parent, _scope.HBM, op.kind, "src.parent")
        _check_scope(dst, _scope.MRAM, op.kind, "dst")
        self._check_slice_single_tile(parent, sl)

        m_off, static_off = self._materialise_slice_offset(parent, sl)
        starts_s = self._format_starts(sl)
        if m_off is None:
            self.shim.compiler.generated_code += (
                f"; dma_h2m_slice  {parent.name}[{starts_s}]+{list(sl.extents)} "
                f"-> {dst.name}  (parent_off={static_off} elems)\n"
            )
            self.emitter.emit_hbm_tile_to_mram(
                hbm_addr=parent.address, mram_addr=dst.address,
                hbm_offset=static_off,
                hbm_scale=parent.hbm_scale_size, hbm_stride=parent.hbm_stride,
            )
        else:
            self.shim.compiler.generated_code += (
                f"; dma_h2m_slice  {parent.name}[{starts_s}]+{list(sl.extents)} "
                f"-> {dst.name}  (parent_off=gp{m_off.register} dyn)\n"
            )
            self.emitter.emit_hbm_tile_to_mram(
                hbm_addr=parent.address, mram_addr=dst.address,
                hbm_offset_reg=m_off.register,
                hbm_scale=parent.hbm_scale_size, hbm_stride=parent.hbm_stride,
            )
            m_off.release()

    def _emit_dma_v2h_slice(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        """Multi-tile-aware writeback dispatcher.

        Output writebacks are the typical multi-tile slice case: BMM_WO
        deposits `eh` mlen*mlen tiles in VRAM head-major; each tile
        becomes one H_STORE_V into the correspondingly-offset region of
        the HBM parent.

        The "BASE" element offset within parent is materialised ONCE
        (either as an int for static slices, or into a GP register via
        ExprMaterializer for dynamic slices). For each per-head tile
        we then add a compile-time constant `h_idx * D` to that base:
            * static: simple int + int
            * dynamic: `S_ADDI_INT tile_off_reg, base_reg, h_idx*D` (or
              reuse base_reg directly when h_idx == 0)
        """
        src = mod.get_buffer(op.buffer_args[0])
        sl = op.buffer_args[1]
        if not isinstance(sl, _hlir.BufferSlice):
            raise IsaEmissionError(
                f"dma_v2h_slice: buffer_args[1] must be BufferSlice"
            )
        parent = mod.get_buffer(sl.parent)
        _check_scope(src, _scope.VRAM, op.kind, "src")
        _check_scope(parent, _scope.HBM, op.kind, "dst.parent")

        ra = self.shim.compiler.register_allocator
        starts_s = self._format_starts(sl)

        m_base, static_base = self._materialise_slice_offset(parent, sl)
        is_dyn = m_base is not None

        self.shim.compiler.generated_code += (
            f"; dma_v2h_slice  {src.name} -> "
            f"{parent.name}[{starts_s}]+{list(sl.extents)}  "
            f"({'dynamic base gp' + str(m_base.register) if is_dyn else 'static base ' + str(static_base)}"
            f", {sl.extents[2]} per-head tiles)\n"
        )

        if self._slice_is_single_logical_tile(parent, sl):
            self.shim.compiler.generated_code += (
                "; ... grouped narrow writeback as one logical mlen*mlen tile\n"
            )
            if is_dyn:
                self.emitter.emit_store_tile_to_hbm(
                    vram_addr=src.address,
                    hbm_addr=parent.address,
                    hbm_stride=parent.hbm_stride,
                    hbm_scale_size=parent.hbm_scale_size,
                    hbm_start_offset_reg=m_base.register,
                )
                m_base.release()
            else:
                self.emitter.emit_store_tile_to_hbm(
                    vram_addr=src.address,
                    hbm_addr=parent.address,
                    hbm_stride=parent.hbm_stride,
                    hbm_scale_size=parent.hbm_scale_size,
                    hbm_start_offset=static_base,
                )
            return

        for h_idx, vram_off, tile_const in self._iter_slice_tiles_per_head(parent, sl):
            tile_vram = src.address + vram_off
            if is_dyn:
                # Dynamic base + compile-time tile_const offset.
                if tile_const == 0:
                    tile_off_reg = m_base.register   # reuse, no extra add
                    tile_off_owned = False
                else:
                    tile_off_reg = ra.allocate_gp(1)[0]
                    tile_off_owned = True
                    self.shim.compiler.generated_code += (
                        f"S_ADDI_INT gp{tile_off_reg}, gp{m_base.register}, "
                        f"{tile_const}\n"
                    )
                self.shim.compiler.generated_code += (
                    f"; ... tile h={h_idx} vram[+{vram_off}] -> "
                    f"hbm[base+{tile_const}]\n"
                )
                self.emitter.emit_store_tile_to_hbm(
                    vram_addr=tile_vram, hbm_addr=parent.address,
                    hbm_stride=parent.hbm_stride,
                    hbm_scale_size=parent.hbm_scale_size,
                    hbm_start_offset_reg=tile_off_reg,
                )
                if tile_off_owned:
                    ra.free_gp([tile_off_reg])
            else:
                tile_hbm_off = static_base + tile_const
                self.shim.compiler.generated_code += (
                    f"; ... tile h={h_idx} vram[+{vram_off}] -> "
                    f"hbm[{tile_hbm_off}]\n"
                )
                self.emitter.emit_store_tile_to_hbm(
                    vram_addr=tile_vram, hbm_addr=parent.address,
                    hbm_stride=parent.hbm_stride,
                    hbm_scale_size=parent.hbm_scale_size,
                    hbm_start_offset=tile_hbm_off,
                )

        if is_dyn:
            m_base.release()

    def _emit_btmm(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        lhs = mod.get_buffer(op.buffer_args[0])
        rhs = mod.get_buffer(op.buffer_args[1])
        dst = mod.get_buffer(op.buffer_args[2])
        _check_scope(lhs, _scope.VRAM, op.kind, "lhs")
        _check_scope(rhs, _scope.MRAM, op.kind, "rhs")
        _check_scope(dst, _scope.VRAM, op.kind, "dst")

        # group_heads = scalar arg (also doubles as expected btmm_lane_count
        # in many of our kernels). We don't currently feed it into the ISA
        # itself -- the BTMM hardware shape is fixed by the program config
        # -- but we keep the value around for future verification.
        if op.scalar_args:
            ghs = int(op.scalar_args[0])
            if ghs != self.shim.btmm_lane_count:
                # Soft warning baked into the ISA stream so we can grep
                # for it; not a hard failure because some kernels deliberately
                # under-fill the lanes.
                self.shim.compiler.generated_code += (
                    f"; WARNING: btmm group_heads={ghs} != program btmm_lane_count="
                    f"{self.shim.btmm_lane_count}\n"
                )

        # Result-tile-count for the writeback. For our minimal_btmm:
        # lhs (mlen, gh, hlen) x rhs (mlen, gh, hlen) -> dst (mlen, gh, mlen)
        # so dst has gh tiles per group, total tile_count = (mlen*gh*mlen)/tile_elems
        tile_count = max(1, dst.num_elements // self.shim.tile_elems)

        self.emitter.emit_btmm(
            lhs_packed_vram_addr=lhs.address,
            rhs_mram_addr=rhs.address,
            task_id=op.annotations.get("intrinsic", "btmm"),
        )
        self.emitter.emit_btmm_wo(
            base_addr=dst.address,
            tile_count=tile_count,
            task_id=op.annotations.get("intrinsic", "btmm") + ".wo",
        )

    def _emit_mm(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        """Single-tile, single-head matrix multiply.

        Maps `plena.mm(lhs_vram, rhs_mram, dst_vram)` to one M_MM /
        M_MM_WO sequence (via ISAEmitter.emit_matmul with a single
        lhs/rhs pair). The dst tile is fully overwritten — no implicit
        accumulation across calls. Streaming-style accumulation is the
        kernel author's job (zero_v + mm + v_add into a separate
        accumulator tile, see kernels/tiled_mm.py).
        """
        lhs = mod.get_buffer(op.buffer_args[0])
        rhs = mod.get_buffer(op.buffer_args[1])
        dst = mod.get_buffer(op.buffer_args[2])
        _check_scope(lhs, _scope.VRAM, op.kind, "lhs")
        _check_scope(rhs, _scope.MRAM, op.kind, "rhs")
        _check_scope(dst, _scope.VRAM, op.kind, "dst")
        lhs_rows, lhs_cols = self._logical_2d(lhs.shape)
        rhs_rows, rhs_cols = self._logical_2d(rhs.shape)
        dst_rows, dst_cols = self._logical_2d(dst.shape)
        if lhs_rows != self.shim.mlen or lhs_cols != self.shim.mlen:
            raise IsaEmissionError(
                f"plena.mm lhs must be one full mlen*mlen tile; got logical 2D "
                f"({lhs_rows}, {lhs_cols}) for buffer {lhs.name}"
            )
        if rhs_rows != self.shim.mlen:
            raise IsaEmissionError(
                f"plena.mm rhs must have mlen rows; got logical 2D "
                f"({rhs_rows}, {rhs_cols}) for buffer {rhs.name}"
            )
        if dst_rows != self.shim.mlen:
            raise IsaEmissionError(
                f"plena.mm dst must have mlen rows; got logical 2D "
                f"({dst_rows}, {dst_cols}) for buffer {dst.name}"
            )
        if rhs_cols != dst_cols:
            raise IsaEmissionError(
                f"plena.mm rhs/dst logical widths must match; got rhs={rhs_cols} dst={dst_cols}"
            )
        # Use the hw-loop emitter (tens of static lines) instead of the
        # Python-unrolled emit_matmul (~2k lines per call). Dynamic
        # instruction count is identical; hw loops just shrink the ISA
        # text. Important for kernels that invoke plena.mm under several
        # unrolled outer levels (q*h*d*kv) where ASM size scales with
        # the product.
        if rhs_cols == self.shim.mlen and dst_cols == self.shim.mlen:
            self.emitter.emit_matmul_single_tile_hwloop(
                lhs_vram_addr=lhs.address,
                rhs_mram_addr=rhs.address,
                dst_vram_addr=dst.address,
                task_id=op.annotations.get("intrinsic", "mm"),
            )
            return
        self.emitter.emit_matmul_narrow_tile_hwloop(
            lhs_vram_addr=lhs.address,
            rhs_mram_addr=rhs.address,
            dst_vram_addr=dst.address,
            hlen=rhs_cols,
            dst_row_stride=dst_cols,
            task_id=op.annotations.get("intrinsic", "mm"),
        )

    def _emit_mm_slot(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        lhs = mod.get_buffer(op.buffer_args[0])
        rhs = mod.get_buffer(op.buffer_args[1])
        dst = mod.get_buffer(op.buffer_args[2])
        _check_scope(lhs, _scope.VRAM, op.kind, "lhs")
        _check_scope(rhs, _scope.MRAM, op.kind, "rhs")
        _check_scope(dst, _scope.VRAM, op.kind, "dst")
        if len(op.scalar_args) != 4:
            raise IsaEmissionError(
                f"plena.mm_slot expects exactly 4 scalar args "
                f"(lhs_row_offset, rhs_col_offset, dst_col_offset, col_count); "
                f"got {len(op.scalar_args)}"
            )
        lhs_row_offset_raw = op.scalar_args[0]
        rhs_col_offset_raw = op.scalar_args[1]
        dst_col_offset_raw = op.scalar_args[2]
        col_count_raw = op.scalar_args[3]
        # lhs_row_offset can be either a compile-time int (literal / IntImm)
        # or a dynamic PrimExpr (e.g. `h * mlen * mlen` from a TIR loop).
        # Static case: fold into the lhs_vram_addr literal.
        # Dynamic case: materialize `lhs.address + offset` to a register and
        # pass that as lhs_vram_addr_reg.
        lhs_addr_m = None
        if isinstance(lhs_row_offset_raw, tir.IntImm):
            lhs_row_offset = int(lhs_row_offset_raw.value)
        elif isinstance(lhs_row_offset_raw, int):
            lhs_row_offset = int(lhs_row_offset_raw)
        elif isinstance(lhs_row_offset_raw, tir.PrimExpr):
            lhs_row_offset = None
            full_addr_expr = tir.Add(
                tir.IntImm("int32", int(lhs.address)),
                lhs_row_offset_raw,
            )
            lhs_addr_m = self.materializer.materialize(full_addr_expr)
            self.shim.compiler.generated_code += lhs_addr_m.isa
        else:
            raise IsaEmissionError(
                f"plena.mm_slot lhs_row_offset must be int or PrimExpr; "
                f"got {type(lhs_row_offset_raw).__name__}: {lhs_row_offset_raw!r}"
            )
        if lhs_row_offset is not None and lhs_row_offset < 0:
            raise IsaEmissionError(
                f"plena.mm_slot lhs_row_offset must be >= 0; got {lhs_row_offset}"
            )
        if isinstance(rhs_col_offset_raw, tir.PrimExpr) and not isinstance(rhs_col_offset_raw, tir.IntImm):
            rhs_col_offset = None
            rhs_off_m = self.materializer.materialize(rhs_col_offset_raw)
            self.shim.compiler.generated_code += rhs_off_m.isa
        else:
            rhs_col_offset = int(rhs_col_offset_raw)
            rhs_off_m = None
        if isinstance(dst_col_offset_raw, tir.PrimExpr) and not isinstance(dst_col_offset_raw, tir.IntImm):
            dst_col_offset = None
            dst_off_m = self.materializer.materialize(dst_col_offset_raw)
            self.shim.compiler.generated_code += dst_off_m.isa
        else:
            dst_col_offset = int(dst_col_offset_raw)
            dst_off_m = None
        try:
            col_count = int(col_count_raw)
        except TypeError as exc:
            raise IsaEmissionError(
                f"plena.mm_slot col_count must be a compile-time integer; got "
                f"{type(col_count_raw).__name__}: {col_count_raw!r}"
            ) from exc
        lhs_rows, lhs_cols = self._logical_2d(lhs.shape)
        rhs_rows, rhs_cols = self._logical_2d(rhs.shape)
        dst_rows, dst_cols = self._logical_2d(dst.shape)
        # LHS must contain at least one mlen*mlen tile. For static offsets
        # we can range-check at compile time; for dynamic offsets the kernel
        # author is responsible for keeping the offset in range.
        tile_elems = self.shim.mlen * self.shim.mlen
        if lhs_row_offset is not None and lhs_row_offset + tile_elems > lhs.num_elements:
            raise IsaEmissionError(
                f"plena.mm_slot lhs tile out of range; "
                f"lhs_row_offset={lhs_row_offset} + mlen*mlen={tile_elems} "
                f"exceeds buffer {lhs.name} num_elements={lhs.num_elements}"
            )
        if rhs_rows != self.shim.mlen or dst_rows != self.shim.mlen:
            raise IsaEmissionError(
                f"plena.mm_slot rhs/dst must have mlen rows; got rhs=({rhs_rows}, {rhs_cols}) "
                f"dst=({dst_rows}, {dst_cols})"
            )
        rhs_col_offset_check = 0 if rhs_col_offset is None else rhs_col_offset
        dst_col_offset_check = 0 if dst_col_offset is None else dst_col_offset
        if rhs_col_offset_check < 0 or dst_col_offset_check < 0 or col_count <= 0:
            raise IsaEmissionError(
                f"plena.mm_slot requires non-negative offsets and positive col_count; got "
                f"rhs_col_offset={rhs_col_offset_raw} dst_col_offset={dst_col_offset_raw} col_count={col_count}"
            )
        if rhs_col_offset is not None and rhs_col_offset + col_count > rhs_cols:
            raise IsaEmissionError(
                f"plena.mm_slot rhs slot exceeds rhs width; rhs_width={rhs_cols} "
                f"rhs_col_offset={rhs_col_offset} col_count={col_count}"
            )
        if dst_col_offset is not None and dst_col_offset + col_count > dst_cols:
            raise IsaEmissionError(
                f"plena.mm_slot dst slot exceeds dst width; dst_width={dst_cols} "
                f"dst_col_offset={dst_col_offset} col_count={col_count}"
            )
        try:
            if lhs_addr_m is not None:
                lhs_vram_addr_arg = 0  # ignored when reg form is used
                lhs_vram_addr_reg = lhs_addr_m.register
            else:
                lhs_vram_addr_arg = lhs.address + lhs_row_offset
                lhs_vram_addr_reg = None
            self.emitter.emit_slot_matmul(
                lhs_vram_addr=lhs_vram_addr_arg,
                lhs_vram_addr_reg=lhs_vram_addr_reg,
                rhs_mram_addr=rhs.address,
                rhs_col_offset=0 if rhs_col_offset is None else rhs_col_offset,
                rhs_col_offset_reg=None if rhs_off_m is None else rhs_off_m.register,
                dst_vram_addr=dst.address,
                dst_col_offset=0 if dst_col_offset is None else dst_col_offset,
                dst_col_offset_reg=None if dst_off_m is None else dst_off_m.register,
                col_count=col_count,
                task_id=op.annotations.get("intrinsic", "mm_slot"),
            )
        finally:
            if rhs_off_m is not None:
                rhs_off_m.release()
            if dst_off_m is not None:
                dst_off_m.release()
            if lhs_addr_m is not None:
                lhs_addr_m.release()

    def _emit_zero_v(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        """Zero an mlen*mlen VRAM tile in-place."""
        dst = mod.get_buffer(op.buffer_args[0])
        _check_scope(dst, _scope.VRAM, op.kind, "dst")
        self.emitter.emit_zero_vram_tile(dst.address)

    def _emit_v_add(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        """VRAM-VRAM tile add: dst = lhs + rhs."""
        lhs = mod.get_buffer(op.buffer_args[0])
        rhs = mod.get_buffer(op.buffer_args[1])
        dst = mod.get_buffer(op.buffer_args[2])
        _check_scope(lhs, _scope.VRAM, op.kind, "lhs")
        _check_scope(rhs, _scope.VRAM, op.kind, "rhs")
        _check_scope(dst, _scope.VRAM, op.kind, "dst")
        self.emitter.emit_tile_add(
            lhs_vram_addr=lhs.address,
            rhs_vram_addr=rhs.address,
            dst_vram_addr=dst.address,
            task_id=op.annotations.get("intrinsic", "v_add"),
        )

    def _emit_map_fp_to_v(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        src = mod.get_buffer(op.buffer_args[0])
        dst = mod.get_buffer(op.buffer_args[1])
        src_addrs = self._fpram_buf_addrs(src, op.kind, "src")
        rows, cols = self._vram_row_shape(dst, op.kind, "dst")
        if len(src_addrs) != rows * cols:
            raise IsaEmissionError(
                f"{op.kind} src fpram length must equal dst elements ({rows * cols}); "
                f"got {len(src_addrs)} for buffer {src.name}"
            )
        self.emitter.emit_map_v_fp_tile(
            vram_addr=dst.address,
            fpram_addr=src.address,
            row_count=rows,
            row_width=cols,
            task_id=op.annotations.get("intrinsic", op.kind),
        )

    def _emit_map_v_to_fp(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        src = mod.get_buffer(op.buffer_args[0])
        dst = mod.get_buffer(op.buffer_args[1])
        rows, cols = self._vram_row_shape(src, op.kind, "src")
        dst_addrs = self._fpram_buf_addrs(dst, op.kind, "dst")
        if len(dst_addrs) != rows * cols:
            raise IsaEmissionError(
                f"{op.kind} dst fpram length must equal src elements ({rows * cols}); "
                f"got {len(dst_addrs)} for buffer {dst.name}"
            )
        self.emitter.emit_map_fp_v_tile(
            fpram_addr=dst.address,
            vram_addr=src.address,
            row_count=rows,
            row_width=cols,
            task_id=op.annotations.get("intrinsic", op.kind),
        )

    def _emit_fp_copy(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_fp_kernel_op(mod, op, kernel_op="copy")
    def _emit_fp_copy_at(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_fp_scalar_op_at(mod, op, kernel_op="copy")

    def _emit_fp_add(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_fp_kernel_op(mod, op, kernel_op="add")
    def _emit_fp_add_at(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_fp_scalar_op_at(mod, op, kernel_op="add")

    def _emit_fp_sub(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_fp_kernel_op(mod, op, kernel_op="sub")
    def _emit_fp_sub_at(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_fp_scalar_op_at(mod, op, kernel_op="sub")

    def _emit_fp_mul(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_fp_kernel_op(mod, op, kernel_op="mul")
    def _emit_fp_mul_at(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_fp_scalar_op_at(mod, op, kernel_op="mul")

    def _emit_fp_max(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_fp_kernel_op(mod, op, kernel_op="max")
    def _emit_fp_max_at(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_fp_scalar_op_at(mod, op, kernel_op="max")

    def _emit_fp_exp(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_fp_kernel_op(mod, op, kernel_op="exp")
    def _emit_fp_exp_at(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_fp_scalar_op_at(mod, op, kernel_op="exp")

    def _emit_fp_reci(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_fp_kernel_op(mod, op, kernel_op="reci")
    def _emit_fp_reci_at(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_fp_scalar_op_at(mod, op, kernel_op="reci")

    def _emit_fp_sqrt(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_fp_kernel_op(mod, op, kernel_op="sqrt")
    def _emit_fp_sqrt_at(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_fp_scalar_op_at(mod, op, kernel_op="sqrt")

    def _emit_row_reduce_max(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op(mod, op, row_op="reduce_max", reduce=True)

    def _emit_row_reduce_sum(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op(mod, op, row_op="reduce_sum", reduce=True)

    def _emit_row_exp(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op(mod, op, row_op="exp")

    def _emit_row_reci(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op(mod, op, row_op="reci")

    def _emit_row_add_fp(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op(mod, op, row_op="add")

    def _emit_row_sub_fp(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op(mod, op, row_op="sub")

    def _emit_row_mul_fp(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op(mod, op, row_op="mul")

    def _emit_row_reduce_max_mask(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op(mod, op, row_op="reduce_max", reduce=True, masked=True)

    def _emit_row_reduce_sum_mask(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op(mod, op, row_op="reduce_sum", reduce=True, masked=True)

    def _emit_row_exp_mask(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op(mod, op, row_op="exp", masked=True)

    def _emit_row_reci_mask(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op(mod, op, row_op="reci", masked=True)

    def _emit_row_add_fp_mask(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op(mod, op, row_op="add", masked=True)

    def _emit_row_sub_fp_mask(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op(mod, op, row_op="sub", masked=True)

    def _emit_row_mul_fp_mask(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op(mod, op, row_op="mul", masked=True)
    # Unified `_at` ops: scalars are the logical (dim2, dim3) indices of the
    # source buffer. The emitter maps that pair to a physical VRAM row and, for
    # narrow packed D tiles, synthesizes the required V_MASK automatically.
    def _emit_row_reduce_max_at(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op_at(mod, op, row_op="reduce_max", reduce=True, masked=True)
    def _emit_row_reduce_sum_at(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op_at(mod, op, row_op="reduce_sum", reduce=True, masked=True)
    def _emit_row_exp_at(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op_at(mod, op, row_op="exp", masked=True)
    def _emit_row_sub_fp_at(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op_at(mod, op, row_op="sub", masked=True)
    def _emit_row_mul_fp_at(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op_at(mod, op, row_op="mul", masked=True)
    def _emit_row_add_fp_at(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        self._emit_row_scalar_op_at(mod, op, row_op="add", masked=True)

    # ------------------------------------------------------------------
    # Structured ops: For
    # ------------------------------------------------------------------
    def _emit_for(self, mod: _hlir.HLIRModule, op: _hlir.Op) -> None:
        """Emit `C_LOOP_START / body / inc / C_LOOP_END` for a structured
        For op.

        PLENA's hardware loop is:
            C_LOOP_START gp_loop, IMM_count
              ...
            C_LOOP_END gp_loop
        where IMM_count is a literal iteration count and gp_loop is an
        internal counter the hardware decrements -- it is NOT the
        iteration index. So we need TWO registers:
            * `gp_loop`  -- hardware counter, opaque to body
            * `gp_idx`   -- body-visible iteration variable, bound to
                            the TIR loop_var via symbol_table; manually
                            initialised before C_LOOP_START and
                            incremented by 1 at the end of every
                            iteration.

        Constraints:
            * extent must be a Python int / IntImm (immediate field of
              C_LOOP_START is a literal). PrimExpr extents are not
              supported -- they would need a compile-time evaluation
              pass or a different lowering (no native loop-with-runtime-
              count instruction in PLENA's ISA).
            * init must be int (typically 0). PrimExpr inits are
              unsupported for the same reason: would force runtime
              loop-bound recomputation.
        """
        loop_var = op.annotations.get("loop_var")
        extent = op.annotations.get("extent")
        init = op.annotations.get("init", 0)
        if loop_var is None or extent is None:
            raise IsaEmissionError(
                f"for-op missing loop_var or extent annotation: {op!r}"
            )
        if not isinstance(extent, (int, tir.IntImm)):
            raise IsaEmissionError(
                f"for-op extent must be a compile-time integer (PLENA's "
                f"C_LOOP_START takes an immediate). Got {type(extent).__name__}: "
                f"{extent!r}. Restructure the kernel so the loop bound is known "
                f"at TIR-construction time."
            )
        if not isinstance(init, (int, tir.IntImm)):
            raise IsaEmissionError(
                f"for-op init must be a compile-time integer. Got "
                f"{type(init).__name__}: {init!r}."
            )
        extent_imm = int(extent.value) if isinstance(extent, tir.IntImm) else int(extent)
        init_imm = int(init.value) if isinstance(init, tir.IntImm) else int(init)
        if loop_var in self.symbol_table:
            raise IsaEmissionError(
                f"loop_var {loop_var.name!r} already bound; nested loops "
                f"reusing the same Var aren't supported."
            )

        ra = self.shim.compiler.register_allocator
        loop_kind = op.annotations.get("loop_kind", "serial")

        # Compile-time unroll: emit the body N times back-to-back with
        # loop_var rebound to a literal each iteration. Use this to break
        # out of MAX_LOOP_INSTRUCTIONS-per-iter when one outer iteration's
        # body would otherwise dispatch too many dynamic instructions
        # (e.g. an inner kv_block accumulation containing a 16x16 unrolled
        # emit_matmul). Costs one S_ADDI_INT per iter to re-init gp_idx;
        # the hardware loop overhead disappears entirely.
        if loop_kind == "unrolled":
            gp_idx = ra.allocate_gp(1)[0]
            self.shim.compiler.generated_code += (
                f"; unroll for {loop_var.name} in "
                f"[{init_imm}, {init_imm + extent_imm}) -- idx gp{gp_idx}\n"
            )
            self.symbol_table[loop_var] = gp_idx
            try:
                for i in range(extent_imm):
                    iter_val = init_imm + i
                    self.shim.compiler.generated_code += (
                        f"; ... unroll iter {i} -> {loop_var.name}={iter_val}\n"
                        f"S_ADDI_INT gp{gp_idx}, gp0, {iter_val}\n"
                    )
                    for sub_op in op.body or []:
                        handler = self._dispatch.get(sub_op.kind)
                        if handler is None:
                            raise IsaEmissionError(
                                f"no ISA dispatcher for nested op kind "
                                f"{sub_op.kind!r} inside unrolled for-loop"
                            )
                        handler(mod, sub_op)
            finally:
                del self.symbol_table[loop_var]
            ra.free_gp([gp_idx])
            return

        # Allocate counter (hardware tracker) and idx (body-visible).
        gp_loop = ra.allocate_gp(1)[0]
        gp_idx = ra.allocate_gp(1)[0]

        self.shim.compiler.generated_code += (
            f"; for {loop_var.name} in [{init_imm}, {init_imm + extent_imm}) "
            f"-- hw counter gp{gp_loop}, idx gp{gp_idx}\n"
            f"S_ADDI_INT gp{gp_idx}, gp0, {init_imm}\n"
            f"C_LOOP_START gp{gp_loop}, {extent_imm}\n"
        )

        self.symbol_table[loop_var] = gp_idx
        try:
            for sub_op in op.body or []:
                handler = self._dispatch.get(sub_op.kind)
                if handler is None:
                    raise IsaEmissionError(
                        f"no ISA dispatcher for nested op kind {sub_op.kind!r} "
                        f"inside for-loop"
                    )
                handler(mod, sub_op)
        finally:
            del self.symbol_table[loop_var]

        self.shim.compiler.generated_code += (
            f"S_ADDI_INT gp{gp_idx}, gp{gp_idx}, 1\n"
            f"C_LOOP_END gp{gp_loop}\n"
        )
        ra.free_gp([gp_loop, gp_idx])


def _check_scope(buf: _hlir.Buffer, expected: str, op_kind: str, role: str) -> None:
    if buf.scope != expected:
        raise IsaEmissionError(
            f"{op_kind} {role} buffer {buf.name!r} must be in scope {expected!r}, "
            f"got {buf.scope!r}"
        )


__all__ = ["IsaEmitterPass", "IsaEmissionError"]
